# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3f182fecaee35f49570c609d7cbfab64f9428bf262bec7c54b3cc3b95d85f8cc32c269ecff44479f3b9c684c0c6f18b9aa18faebe9dd21103906ced205fc21a

test:
  secret_key_base: dc01f0f09afafba9240b119784354ea31ff62215a5359d8fc47818fae5a55c51a5b30718327724ccc15e2be48187433b005b0d6bcb766ce391838e6ff861d87a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
